name: Telegram Test

on:
  workflow_dispatch:

jobs:
  send_message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install requests
        run: pip install requests

      - name: Run script
        run: python telegram_test.py
